# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for GitHub
        uses: shimataro/ssh-key-action@v2.0.2
        with:
          # SSH private key
          key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
          known_hosts: "|1|l1L1sm1HKB816BztFJwUKlMUrGU=|KKePg3JSOPTtitvO4BxliEurMR4= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Lando
        env:
          MY_GITHUB_TOKEN: ${{ secrets.GIT_RATE_TOKEN }}
          MAGE_PRIVATE_KEY: ${{ secrets.MAGENTO_PRIVATE_KEY }}
          MAGE_PUBLIC_KEY: ${{ secrets.MAGENTO_PUBLIC_KEY }}
        run: sudo apt-get -y update
          && sudo apt-get -y install cgroup-bin curl
          && curl -fsSL -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-rrc.3/lando-v3.0.0-rrc.3.deb
          && sudo dpkg -i /tmp/lando-latest.deb
      - name: Lando Version
        run: lando version
      - name: Install packages
        run: yarn --cwd .init.project.tmp test
      - run: yarn --cwd .init.project.tmp test
